# Generated by Django 3.0.7 on 2020-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car')),
                ('car_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=0.0, max_digits=9, null=True)),
                ('gear', models.CharField(choices=[('auto', 'Auto'), ('manula', 'Manual')], default='auto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
