# Generated by Django 3.0.7 on 2020-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(blank=True, choices=[('auto', 'Auto'), ('manula', 'Manual')], default='auto', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
