# Generated by Django 3.0.7 on 2020-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20200623_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='car_category', to='car.Category'),
        ),
    ]
