# Generated by Django 3.0.7 on 2020-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20200624_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_category',
            field=models.ManyToManyField(blank=True, related_name='car_category', to='car.Category'),
        ),
    ]
