# Generated by Django 3.0.7 on 2020-06-23 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraBenifit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('payoneer', 'Payoneer'), ('visacard', 'Visa Card')], default='paypal', max_length=15)),
                ('additional_info', models.TextField()),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('drop_off_location', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_off_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_car', to='car.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('extra_benifits', models.ManyToManyField(related_name='extra_benifit', to='booking.ExtraBenifit')),
            ],
        ),
    ]
