# Generated by Django 3.0.7 on 2020-06-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20200624_1226'),
        ('booking', '0002_auto_20200623_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBookingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('drop_off_location', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_off_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_booking_car', to='car.Car')),
            ],
        ),
        migrations.AddField(
            model_name='bookingcar',
            name='quick_booking',
            field=models.ManyToManyField(blank=True, null=True, to='booking.QuickBookingCar'),
        ),
    ]
