# Generated by Django 3.0.7 on 2020-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200624_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbookingcar',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='quickbookingcar',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='bookingcar',
            name='quick_booking',
            field=models.ManyToManyField(blank=True, to='booking.QuickBookingCar'),
        ),
    ]
