# Generated by Django 3.0.7 on 2020-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200624_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcar',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
