# Generated by Django 3.0.6 on 2020-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200626_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookingcar',
            name='benifits',
            field=models.ManyToManyField(to='booking.ExtraBenifit'),
        ),
    ]
