# Generated by Django 3.0.6 on 2020-07-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_quickbookingcar_benifits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingCar',
        ),
    ]
