# Generated by Django 3.0.6 on 2020-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_bookingcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookingcar',
            name='info',
            field=models.CharField(blank=True, max_length=500, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='quickbookingcar',
            name='payment',
            field=models.CharField(blank=True, max_length=10, null='True'),
            preserve_default='True',
        ),
    ]
