# Generated by Django 3.0.7 on 2020-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_officetimelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='banner')),
                ('foreground_image', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
