# Generated by Django 3.0.7 on 2020-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(blank=True, max_length=100)),
                ('feature_description', models.TextField()),
                ('feature_image', models.ImageField(upload_to='feature')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_icon_name', models.CharField(blank=True, max_length=100)),
                ('feature_item_title', models.CharField(blank=True, max_length=100)),
                ('feature_item_description', models.TextField()),
            ],
        ),
    ]
